version: '3.8'
services:
  web:
    build: .
    ports:
      - '3000:3000'
    environment:
      REACT_APP_MARKETPLACE_ADDR: 0x0000000000000000000000000000000000000000
      REACT_APP_NFT_ADDR: 0x0000000000000000000000000000000000000000
      REACT_APP_INFURA_PROJECT_ID: 00000000000000000000000000000000
      REACT_APP_METADATA_BASE_URL: https://ipfs.io/ipfs/metdataUrl
      REACT_APP_IMAGE_BASE_URL: https://ipfs.io/ipfs/imagesUrl
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules